### ISSUE TITLE
Resource Error-Not found

### ISSUE THREAD

**Issue by usa4cc** [Franciscan-CS-Club/Franciscan-CS-Club.github.io#22]
The following resource appears to not be working correctly:
https://franciscan-cs-club.github.io/rain.mp4

Go to Developer Tools (F12), console, and then refresh the page to see the issue.

**Comment by 2br-2b** [comment]
Fixed by https://github.com/Franciscan-CS-Club/Franciscan-CS-Club.github.io/commit/8b709b6e07a77bda9aa68613ae9f38c506c77ca4
